config/routes.rb
Flashcards1::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :selections, only: [:create, :destroy]
  resources :cardsets do
    resources :cards do
      resources :levels
    end
  end

  root 'static_pages#home'
  match '/signup',  to: 'users#new',				via: 'get'
  match '/signin',  to: 'sessions#new',			via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  

  

end

app/models/cardset.rb
class Cardset < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :cards,      dependent: :destroy
  has_many :selections, dependent: :destroy
  has_many :users, through: :selections
  validates :author_id, presence: true
  validates :topic,     presence: true

  def max_order(status, user_id)
    cards.joins(:levels).where(levels: { status: status, user_id: user_id }).maximum(:sort_order) || 0
  end
end

app/controllers/cardsets_controller.rb
class CardsetsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @cardsets = Cardset.all
  end

  def new
    @cardset = Cardset.new
  end

  def create
    @cardset = Cardset.new(cardset_params.merge(author_id: current_user.id))
    if @cardset.save
      flash[:success] = "A new set of cards is created!"
      redirect_to @cardset
    else
      render 'new'
    end
  end

  def show
    @cardset = Cardset.find(params[:id])
    @cards = @cardset.cards.with_levels_for(current_user.id).group_by_level(current_user)   
  end

  def edit
    @cardset = Cardset.find(params[:id])
  end

  def update
    @cardset = Cardset.find(params[:id])
    if @cardset.update_attributes(cardset_params)
      flash[:success] = "The card set is updated!"
      redirect_to @cardset
    else
      render 'edit'
    end
  end

  def destroy
    @cardset.destroy
    redirect_to current_user
  end

  private
    def cardset_params
      params.require(:cardset).permit(:topic, :description)
    end

    def correct_user
      cardset = Cardset.find(params[:id])
      if cardset.author_id != current_user.id
        flash[:error] = "You have to be owner of the cardset!"
        redirect_to current_user
      end
    end
end

app/views/cardsets/edit.html.erb
<%= provide(:title, "Edit card set") %>
<h1>Edit card set: <%= @cardset.topic %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@cardset) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :topic %>
      <%= f.text_field :topic %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.submit "Save changes", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/cardsets/index.html.erb
<%= provide(:title, 'All cardsets') %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>Cardsets</h1>
      <% @cardsets.each do |cardset| %>
        <p>
          <%= cardset.topic %>
          <% if cardset.cards.any? %>
            | <%= pluralize(cardset.cards.count, "card") %>
          <% end %>
          <% if cardset.users.any? %>
            | <%= pluralize(cardset.users.count, "learner") %>
          <% end %>
          <% if current_user.cardsets.include?(cardset) %>
            | already selected
          <% else %>
            | <%= link_to "Select to learn", selections_path(selection: { cardset_id: cardset.id }), method: :post %>
          <% end %>
        </p>
      <% end %>
    </section>
  </aside>
</div>

app/views/cardsets/new.html.erb
<% provide(:title, 'New set of cards') %>
<h1>Create a new set of cards</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@cardset) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :topic %>
      <%= f.text_field :topic %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.submit "Create a new set of cards", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/cardsets/show.html.erb
<%= provide(:title, @cardset.topic) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>Overview <%= @cardset.topic %></h1>
      <p><%= @cardset.description %></p>
      <% @cards.each do |status, cards| %>
        <% if cards.first.levels.where(user_id: current_user.id).empty? %>
          <p><%= link_to "Learn Level #{status}", new_cardset_card_level_path(@cardset, cards.first) %></p>
          <p><%= cards.count %> Cards</p>
          <% cards.each do |card| %>
            <p>
              <%= card.question %> | id: <%= card.id %> | level: <%= card.level_for_user(current_user).try(:status) || 0 %>
              | sort_order: <%= card.level_for_user(current_user).try(:sort_order) || 0 %>
            </p>
          <% end %>
        <% else %>
          <p><%= link_to "Learn Level #{status}", edit_cardset_card_level_path(@cardset, cards.first, cards.first.levels.where(user_id: current_user.id).first.id) %></p>
          <p><%= cards.count %> Cards</p>
          <% cards.each do |card| %>
            <p>
              <%= card.question %> | id: <%= card.id %> | level: <%= card.level_for_user(current_user).status %>
              | sort_order: <%= card.level_for_user(current_user).sort_order %>
            </p>
          <% end %>
        <% end %>
      <% end %>
    </section>
  </aside>
</div>