config/routes.rb
Flashcards1::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :selections, only: [:create, :destroy]
  resources :cardsets do
    resources :cards do
      resources :levels
    end
  end

  root 'static_pages#home'
  match '/signup',  to: 'users#new',				via: 'get'
  match '/signin',  to: 'sessions#new',			via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :selections
  has_many :cardsets, through: :selections
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,	only: [:show, :edit, :update]
  before_action :correct_user,		only: [:show, :edit, :update]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Flashcards App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.cardsets.any? %>
      <h3>Your Card Sets (<%= @user.cardsets.count %>)</h3>
      <ol class="cardsets">
        <% @user.cardsets.each do |cardset| %>
          <li>
            <span class="topic"><%= cardset.topic %> (<%= cardset.cards.count %> cards)</span>
            <% if cardset.cards.any? %>
              <%= link_to "learning", cardset_path(cardset) %> |
              <%= link_to "show all cards", cardset_cards_path(cardset) %> |
            <% end %>
            <%= link_to "add a card", new_cardset_card_path(cardset) %>
            | <%= link_to "edit", edit_cardset_path(cardset) %>
            | <%= link_to "delete", cardset,  method: :delete,
                                    data: { confirm: "You sure?" },
                                    title: cardset.topic %>
          </li>
        <% end %>
      </ol>
    <% else %>
      <p>You have no card sets yet.</p>
      <p><%= link_to "Create a new card set.", new_cardset_path %></p>
    <% end %>
  </div>
</div>