config/routes.rb
Flashcards1::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :selections, only: [:create, :destroy]
  resources :cardsets do
    resources :cards do
      resources :levels
    end
  end

  root 'static_pages#home'
  match '/signup',  to: 'users#new',				via: 'get'
  match '/signin',  to: 'sessions#new',			via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  

  

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :cardset
  has_many :levels, dependent: :destroy
  has_many :users, through: :levels
  validates :cardset_id,	presence: true
  validates :question,		presence: true
  validates :answer, 			presence: true

  def self.with_levels_for(user_id)    
    sql = sanitize_sql_array(['LEFT OUTER JOIN levels ON cards.id = levels.card_id AND levels.user_id = ?', user_id])
    cards = joins(sql).order_by_level
  end

  def self.with_status(status)
    status = [0, nil] if status.nil? || status == 0
    includes(:levels).where(:levels => { :status => status })
  end

  def self.order_by_level
    order('levels.status IS NOT NULL, levels.status, levels.sort_order IS NOT NULL, levels.sort_order, cards.id')
  end

  def self.group_by_level(user)
    all.group_by { |card| card.level_for_user(user).try(:status) || 0 }
  end

  def level_for_user(user)
    levels.where(user_id: user.id).first
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @cards = Cardset.find(params[:cardset_id]).cards
  end

  def new
    @cardset = Cardset.find(params[:cardset_id])
    @card = Card.new
  end

  def create
    @cardset = Cardset.find(params[:cardset_id])
    @card = @cardset.cards.build(card_params)
    if @card.save
      flash[:success] = "A new card is created!"
      redirect_to cardset_card_path(@card.cardset_id, @card.id)
    else
      render 'new'
    end
  end

  def show
    @cardset = Cardset.find(params[:cardset_id])
    @card = Card.find(params[:id])
  end

  def edit
    @cardset = Cardset.find(params[:cardset_id])
    @card = Card.find(params[:id])
  end

  def update
    @cardset = Cardset.find(params[:cardset_id])
    @card = Card.find(params[:id])
    if @card.update_attributes(card_params)
      flash[:success] = "Card is updated!"
      redirect_to cardset_card_path(@card.cardset_id, @card.id)
    else
      render 'edit'
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to current_user
  end

  private
    def card_params
      params.require(:card).permit(:question, :answer, :cardset_id)
    end
end

app/views/cards/edit.html.erb
<% provide(:title, 'Edit card') %>
<h1>Edit card</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for [@cardset, @card] do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :question %>
			<%= f.text_area :question %>

			<%= f.label :answer %>
			<%= f.text_area :answer %>

			<%= f.submit "Save changes", class: "btn" %>
		<% end %>
	</div>
</div>

app/views/cards/index.html.erb
<%= provide(:title, 'All Cards') %>
<div class="row">
	<aside class="span4">
		<section>
			<h2>Questions</h2>
			<% @cards.each do |card| %>
				<p><%= card.question %></p>
				<p><%= link_to "Edit card", edit_cardset_card_path(card.cardset, card) %></p>
				<p><%= link_to "Delete card", cardset_card_path(card.cardset, card),
																			method: :delete,
																			data: { confirm: "You sure?" } %></p>
			<% end %>
		</section>
	</aside>
</div>

app/views/cards/new.html.erb
<% provide(:title, 'New card') %>
<h1>Create a new card</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for [@cardset, @card] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :question %>
      <%= f.text_area :question %>

      <%= f.label :answer %>
      <%= f.text_area :answer %>

      <%= f.submit "Create a new card", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/cards/show.html.erb
<%= provide(:title, Card) %>
<div class="row">
  <aside class="span4">
    <section>
      <h2>Question</h2>
      <p><%= @card.question %></p>
      <h2>Answer</h2>
      <p><%= @card.answer %></p>
      <p>created in cardset: <%= @card.cardset.topic %></p>
      <p><%= link_to "Edit card", edit_cardset_card_path(@cardset, @card) %></p>
      <p><%= link_to "Delete card", cardset_card_path(@cardset, @card),
                                    method: :delete,
                                    data: { confirm: "You sure?" } %></p>
      <p><%= link_to "Create new card", new_cardset_card_path(@cardset) %></p>
    </section>
  </aside>
</div>